### ISSUE TITLE
May I have some more sir?

### ISSUE THREAD

**Issue by builderjer** [JarbasAI/skill_easter_eggs#28]
There are several other skills floating around similar to Duke Nukem and I think it would be fun to include them.

https://github.com/Quinn2017/Skill-Bill-and-Teds
https://github.com/KathyReid/skill-malibu-stacy
https://github.com/aussieW/skill-farting
https://github.com/EuripideH/skill-bouddha
https://github.com/aussieW/skill-confucius-say

I am sure there are a few more, but here is a start.

**Comment by JarbasAl** [comment]
https://github.com/JarbasSkills/skill-confucius-quotes  i got this one updated

**Comment by builderjer** [comment]
Just found another
https://github.com/JarbasSkills/skill-pickup-lines

**Comment by mikejgray** [comment]
Will add these in, since they're pretty small:

https://github.com/Quinn2017/Skill-Bill-and-Teds
https://github.com/KathyReid/skill-malibu-stacy

These should probably be their own thing:
https://github.com/aussieW/skill-farting
https://github.com/EuripideH/skill-bouddha
https://github.com/JarbasSkills/skill-confucius-quotes 
https://github.com/JarbasSkills/skill-pickup-lines

I'm wary of getting too crazy adding intents in a single skill when the current intent engines scale poorly with number of intents, plus those other skills are unique enough to warrant specific installation, and don't necessarily fit the theme of movies/TV show Easter Eggs. Open to conversation on it though

**Comment by builderjer** [comment]
To me, most are "What would ____ say?".  Maybe farting and pickup-lines are different, but....hmmmm.  Could the intents be condensed somehow to just pickup the keyword of the blank above?

**Comment by mikejgray** [comment]
It's not so much that it doesn't fit the general pattern of "What would ___ say," but that most of them are generally standalone kind of skills. If you want your assistant to fart, you should probably explicitly install that skill. Same idea with pickup lines, confucius quotes, and buddha quotes. I'd personally rather see them get added to a skillstore, maybe with a modernized fork/branch, versus adding them all into this skill. Nothing preventing us from using this as boilerplate to modernize the others

**Comment by mikejgray** [comment]
@builderjer @JarbasAl For the sake of both making things explicit for users and also boosting the numbers in the skillstore, I'd like to close this issue out in favor of modernizing/re-creating the skills listed above. Thoughts?

**Comment by builderjer** [comment]
Sounds good to me.  @JarbasAl  can reopen if he feels otherwise.
